### ISSUE TITLE
Some versions of Numpy in PyPi giving error 

### ISSUE THREAD

**Issue by jobin1986** [sonatype-nexus-community/sonatype-platform-browser-extension#86]
**Describe the bug**
There is a block of versions of Numpy in Pypi that are not working with the platform extension

**To Reproduce**
1. Go to https://pypi.org/project/numpy/1.14.0/
2. Click on Sonatype Platform Extension
3. See error "Aw shucks! We could not find that peanut in a haystack!"

**Expected behavior**
Expecting the extension to work with Numpy versions 1.11.3 to 1.22.
Expecting to see Numpy versions 1.11.3 to 1.22 in the remediation column of the extension when analysing a version that is working with the extension e.g. Numpy==1.11.1
 

**Screenshots**
![Screenshot 2023-09-05 at 11 56 21](https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/84018231/2741eaa5-f381-4383-8eac-1b4747a9f355)
![Screenshot 2023-09-05 at 11 57 06](https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/84018231/96824540-20ff-4b34-908b-6abd2451e3f3)
![Screenshot 2023-09-05 at 11 58 11](https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/84018231/67d76d42-0c10-436b-8d54-3d18c6b4afe0)

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Browser: Chrome
 - Version: 116.0.5845.140 (Official Build) (x86_64)

**Comment by madpah** [comment]
Thanks for the report @jobin1986 - this is no totally unexpected given the current implementation.

Python Packages can (generally) be `.whl` or `.tar.gz`. `.whl` packages are architecture and platform specific (potentially), and the Platform Browser Extension cannot (and does not) assume knowledge of your target architecture or platform - thus we revert to assuming the source package (with an extension of `.tar.gz`).

The package versions you have reported DO NOT HAVE `.tar.gz` source packages - they have `.zip` packages, which is why they are not matching data.

Whilst this appears as a BUG, it is really a request for an Improvement here (similar to #85 for Java).
